<<<<<<< HEAD

// FUNÇÃO - FORMA EXPRESSIVA (EXPRESSÃO DE FUNÇÃO)

// console.log(soma(1,8)) -> A FUNÇÃO EXPRESSIVA NÃO PODE SER EXECUTADA ANTES SER CRIADA 

const soma = function(num1, num2){

	return num1 + num2
}

console.log(soma(1,8))


// EXPRESSÃO DE FUNÇÃO -> É UMA FUNÇÃO ANONIMA OU SEJA NÃO TEM NOME



// PRINCIPAL DIFERENÇA "FUNÇÃO DECLARATIVA" PARA A "FUNÇÃO EXPRESSIVA": É O HOISTING 


// FUNÇÃO DECLARATIVA
console.log(apresentar()) // FUNÇÃO SENDO EXECUTA ANTES DE SER CRIADA

function apresentar(){
	return "Olá";
}


/*
>>> HOISTING (IÇAR OU LEVANTAR)

ANTES DE EXECUTAR OS CÓDIGOS DO PROGRAMA O JAVASCRIPT LISTA TODAS AS FUNÇÕES DECLARATIVAS E TODAS AS VAR (VARIÁVEIS) E CARREGA PARA 
O INICIO DO PROGRAMA E SÓ DEPOIS COMEÇA A EXECUTAR AS LINHA DE CÓDIGO.

ISSO NÃO ACONTECE COM AS FUNÇÕES EXPRESSIVAS.

=======

// FUNÇÃO - FORMA EXPRESSIVA (EXPRESSÃO DE FUNÇÃO)

// console.log(soma(1,8)) -> A FUNÇÃO EXPRESSIVA NÃO PODE SER EXECUTADA ANTES SER CRIADA 

const soma = function(num1, num2){

	return num1 + num2
}

console.log(soma(1,8))


// EXPRESSÃO DE FUNÇÃO -> É UMA FUNÇÃO ANONIMA OU SEJA NÃO TEM NOME



// PRINCIPAL DIFERENÇA "FUNÇÃO DECLARATIVA" PARA A "FUNÇÃO EXPRESSIVA": É O HOISTING 


// FUNÇÃO DECLARATIVA
console.log(apresentar()) // FUNÇÃO SENDO EXECUTA ANTES DE SER CRIADA

function apresentar(){
	return "Olá";
}


/*
>>> HOISTING (IÇAR OU LEVANTAR)

ANTES DE EXECUTAR OS CÓDIGOS DO PROGRAMA O JAVASCRIPT LISTA TODAS AS FUNÇÕES DECLARATIVAS E TODAS AS VAR (VARIÁVEIS) E CARREGA PARA 
O INICIO DO PROGRAMA E SÓ DEPOIS COMEÇA A EXECUTAR AS LINHA DE CÓDIGO.

ISSO NÃO ACONTECE COM AS FUNÇÕES EXPRESSIVAS.

>>>>>>> 0ff5f46256d56b5c9e17582ef79acb03565c69ac
*/